from businessModule.apiRigister.requestRigister import rigister
from businessModule.apiRigister.flaskIndexApiDataConfig import desc, notes
from businessModule.business.adInfoComposing.getData import create_campaign_name